#cloud-config
install:
  poweroff: true
stages:
  before-install:
    - name: "Remove machine-id"
      if: '[ -f "/run/cos/live_mode" ]'
      commands:
        - echo -n > /etc/machine-id
  initramfs:
    - users:
        kairos:
          groups:
            - sudo
          passwd: kairos
      name: "Create kairos user"
