#cloud-config
install:
  reboot: false
  poweroff: true
stylus:
  debug: false
stages:
  before-install:
    - name: "Remove machine-id"
      if: '[ -f "/run/cos/live_mode" ]'
      commands:
        - echo -n > /etc/machine-id
  initramfs:
    - users:
        kairos:
          groups:
            - sudo
          passwd: "j4UN#YPQK/#r"
      name: "Create kairos user"
