#cloud-config
install:
  reboot: false
  poweroff: true
stylus:
  debug: false
stages:
  before-install:
    - name: "Remove machine-id"
      if: '[ -f "/run/cos/live_mode" ]'
      commands:
        - echo -n > /etc/machine-id
  after-install:
    - name: "Delete mounted user data"
      if: '[ -f "/run/cos/live_mode" ]'
      commands:
        - rm -f /oem/userdata*
  initramfs:
    - users:
        kairos:
          groups:
            - sudo
          passwd: kairos
      name: "Create kairos user"
